version: '3.1' 
services:
  rmq:
    image: rabbitmq:3.8.3-alpine
    container_name: rmq
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    image: worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/tmp
    depends_on:
    - rmq
    restart: on-failure

  orchestrator:
    container_name: orchestrator
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && python -u orchestrator.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - .:/tmp
    ports:
      - 80:80
    expose:
        - "80"
    restart: on-failure