version: '3.1'

services:
  rmq:
    image: rabbitmq
    container_name: rmq
    ports:
      - 5672:5672
      - 15672:15672

  master:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 40 && python -u master.py"
    volumes:
        - .:/tmp
    links:
    - rmq
    depends_on:
    - rmq
    restart: on-failure

  slave:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 10 && python -u slave.py"
    volumes:
        - .:/tmp
    links:
    - rmq
    depends_on:
    - rmq
    restart: on-failure

  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 10 && python -u orchestrator.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - .:/tmp
    ports:
      - 80:80
    expose:
        - "80"
    restart: on-failure    